### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by rootnegativ1** [rootnegativ1/unifi-wifi#1]
- [ ] should the minimum character count be increased to 12 to align with current UniFi trends?
- [ ] add poweroff / reboot commands. This feels like feature creep so maybe
- [ ] decide if a continuously logged-in session is needed. This would allow changes to be immediately observed rather than based off ```update_interval```. (e.g. currently a password can be changed then reverted before the component notices)
- [ ] make integration configurable through the UI (move away from configuration.yaml entries to config_flow)
- [ ] add tests https://github.com/MatthewFlamm/pytest-homeassistant-custom-component to the integration
- [ ] add info to home-assistant/brands to allow for a complete HACS validation action (currently ignored) and inclusion to HACS in general
- [ ] figure out a reasonable workflow between branches to help in generating useful changelogs for releases
- [ ] get better at python

**Comment by rootnegativ1** [comment]
WPA3 SAE only info:
https://superuser.com/questions/1752083/wifi-qr-code-format-for-wpa2-wpa3
https://www.wi-fi.org/system/files/WPA3%20Specification%20v3.2.pdf#page=25
https://community.ui.com/questions/Looking-for-QR-Code-or-alternatives-for-WPA3-How-to-quickly-connect-clients-to-WPA3-only-networks/43450e96-bcc9-4959-98ee-b8e2266d1a1a

**Comment by rootnegativ1** [comment]
https://community.ui.com/questions/12-Character-Password-Requirement-is-Stupid/84a7f8e8-04db-4131-8e09-d6990d483047
